
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AdminTestimonialsPage = lazy(() => import("./pages/AdminTestimonialsPage.tsx"));
const App = lazy(() => import("./pages/App.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-testimonials-page", element: <AdminTestimonialsPage />},
	{ path: "/admintestimonialspage", element: <AdminTestimonialsPage />},
	{ path: "/", element: <App />},

];
